services:
  softioc:
    extends:
      file: compose.yaml
      service: softioc

  epics2web:
    extends:
      file: compose.yaml
      service: epics2web
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - CUSTOM_CRT_URL=http://pki.jlab.org/JLabCA.crt