services:
  softioc:
    extends:
      file: deps.yml
      service: softioc

  epics2web:
    hostname: epics2web
    container_name: epics2web
    environment:
      EPICS_CA_ADDR_LIST: softioc
    depends_on:
      - softioc
    ports:
      - 8080:8080
